version: "3"

services:

  networksandbox:
    image: k8s.gcr.io/pause

  eos1100d:
    privileged: true
    image: nixery.dev/shell/ffmpeg/gphoto2
    command:
    - sh
    - -c
    - |
      gphoto2 --stdout --capture-movie \
      | ffmpeg -i - -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video8

  tuning:
    privileged: true
    image: nixery.dev/shell/v4l-utils
    command:
    - sh
    - -c
    - |
      v4l2-ctl --device /dev/video0 -c power_line_frequency=1
      v4l2-ctl --device /dev/video2 -c power_line_frequency=1
      v4l2-ctl --device /dev/video2 -c focus_auto=1

  v4l2loopback:
    privileged: true
    image: alpine
    command: modprobe v4l2loopback video_nr=8,9 card_label=EOS1100D,OBS
    volumes:
    - /lib/modules:/lib/modules

  alsaloopback:
    privileged: true
    image: alpine
    command: modprobe snd-aloop index=9 id=Loopback pcm_substreams=1
    volumes:
    - /lib/modules:/lib/modules

  obs:
    privileged: true
    network_mode: "service:networksandbox"
    ipc: host
    build:
      context: obs-studio
      dockerfile: Dockerfile.ubuntu
    environment:
    - DISPLAY
    - HOME
    - USER
    volumes:
    - /tmp/.X11-unix/:/tmp/.X11-unix/
    - $HOME/.config/obs-studio:$HOME/.config/obs-studio
    - /etc/passwd:/etc/passwd:ro
    - /etc/shadow:/etc/shadow:ro
    - /etc/group:/etc/group:ro
    - $HOME/Downloads:$HOME/Downloads
    - /run/user/$UID/pulse/:/var/run/pulse/
    - ./data/:/data/
    - /usr/lib/x86_64-linux-gnu/:/local-libraries/:ro
    command:
    - sh
    - -c
    - |
      chown ${UID:?please 'export UID'} $HOME/.config/obs-studio
      xset -dpms
      xset s off
      if [ -d /local-libraries ]; then
        cp -a /local-libraries/libnv* /usr/lib/x86_64-linux-gnu/
        cp -a /local-libraries/nvidia/current/* /usr/lib/x86_64-linux-gnu/
      fi
      su $USER sh -c obs
      #su -G video $USER sh -c obs

  streamdeck:
    privileged: true
    network_mode: "service:networksandbox"
    build: streamdeck
    environment:
    - DISPLAY
    - HOME
    - USER
    - PATH=/scripts:/usr/local/bin:/usr/bin:/bin
    volumes:
    - /tmp/.X11-unix/:/tmp/.X11-unix/
    - $HOME/.config/streamdeck_ui:$HOME
    - /etc/passwd:/etc/passwd:ro
    - /etc/shadow:/etc/shadow:ro
    - /etc/group:/etc/group:ro
    - ./bin/:/scripts/:ro
    - ./data/:/data/
    working_dir: /data
    command:
    - sh
    - -c
    - |
      chown ${UID:?please 'export UID'} $HOME
      su -G plugdev -G input -G video $USER sh -c streamdeck

  countdown:
    image: python:3
    volumes:
    - /etc/passwd:/etc/passwd:ro
    - /etc/shadow:/etc/shadow:ro
    - ./bin:/usr/local/bin
    - ./data/:/data/
    working_dir: /data
    command:
    - sh
    - -c
    - |
      su $USER sh -c "countdown _"

